# -*- coding: utf-8 -*-
"""Passion Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OhojvnKNw-jbD-rSUMAWAqcc-Z2ZTwKR
"""

# Trendy Clothing category

clothing_brands = ["Nike", "American Eagle", "H&M", "Adidas", "Zara", "Lululemon"]

clothing_prices_2025 = [22.50,20.98,14.99,78,47.94,64]

clothing_prices_2026 = [75,58.45,22.99,80,39.6,88]

clothing_average_2025 = (sum(clothing_prices_2025)/6)

clothing_average_2026 = (sum(clothing_prices_2026)/6)

clothing_inflation_rate = (((clothing_average_2026 - clothing_average_2025)/clothing_average_2025)*100)

# Fast Food brands category

Fast_foods = ["Subway", "Starbucks", "Chipotle", "Taco Bell", "McDonald"]

Fast_food_price_2025 = [8.49,3.05,11.35,1.39,10.69]

Fast_food_price_2026 = [11.39,3.75,10.80,1.29,12.59]

fast_food_average_2025 = (sum(Fast_food_price_2025)/5)

fast_food_average_2026 = (sum(Fast_food_price_2026)/5)

fast_food_inflation_rate = (((fast_food_average_2026 - fast_food_average_2025)/fast_food_average_2025)*100)

# Movie Theater Chains category

Movie_Theater_Chains = ["AMC", "Regal", "Cinemark", "Cinepolis", "Alamo Drafthouse"]

Movie_Theater_Chains_price_2025 = [25,15.75,16.08,19,14.25]

Movie_Theater_Chains_price_2026 = [18,16.08,14.5,17,14.88]

Movie_theater_average_2025 = (sum(Movie_Theater_Chains_price_2025)/5)

Movie_theater_average_2026 = (sum(Movie_Theater_Chains_price_2026)/5)

Movie_theater_inflation_rate = (((Movie_theater_average_2026 - Movie_theater_average_2025)/Movie_theater_average_2025)*100)

# Gifts_choosing category

Gift_Items = ["Art", "Skincare", "Makeup", "Toys", "Decorative Objects"]

Gift_Items_price_2025 = [24,36,49,23.45,45.64]

Gift_Items_price_2026 = [32,45,60,34.56,43.23]

gift_items_average_2025 = (sum(Gift_Items_price_2025)/5)

gift_items_average_2026 = (sum(Gift_Items_price_2026)/5)

gift_items_inflation_rate = (((gift_items_average_2026 - gift_items_average_2025)/gift_items_average_2025)*100)

# Streaming category

Streaming = ["Spotify", "Apple TV", "Youtube", "Netflix", "HBO Max"]

Streaming_prices_2025 = [11.99,12.99,13.99,17.99,18.49]

Streaming_prices_2026 = [12.99,12.99,15.99,19.99,18.49]

Streaming_average_2025 = (sum(Streaming_prices_2025)/5)

Streaming_average_2026 = (sum(Streaming_prices_2026)/5)

Streaming_inflation_rate = (((Streaming_average_2026 - Streaming_average_2025)/Streaming_average_2025)*100)

# Overall Teen Inflation Rate

overall_teen_girls_inflation_rate = (((clothing_inflation_rate + fast_food_inflation_rate + Movie_theater_inflation_rate + gift_items_inflation_rate + Streaming_inflation_rate )/5))

# Interactive Persona Quiz

ask_job = input("Do you have a job? (Yes or No): ")

if ask_job == "Yes" or ask_job == "yes":

  weekly_income = float(input("What is your weekly allowance or income? "))

else:

  print("Understood. Thanks!")

# Next Questions

hours_needed = float(input("Approximately how much do you spend each week? "))

money_category = input("What category(Trendy Clothing, Fast Foods, Movie Theaters ,Gifts, and Streaming) do you spend the most money on? ")

purchasing_loss = hours_needed * (overall_teen_girls_inflation_rate /100)

# Specific Category Inflation Rate

user_category_rate = 0.0

if "trendy clothing" in money_category.lower() or "trendy clothing" in money_category.lower() or "trendy clothing" in money_category.lower() or "clothing" in money_category.lower() or "clothing" in money_category.lower():
  user_category_rate = clothing_inflation_rate

elif "fast foods" in money_category.lower() or "fast foods" in money_category.lower() or "fast foods" in money_category.lower() or "foods" in money_category.lower() or "food" in money_category.lower():
  user_category_rate = fast_food_inflation_rate

elif "movie theaters" in money_category.lower() or "movie theaters" in money_category.lower() or "movie theaters" in money_category.lower() or "movie" in money_category.lower() or "movies" in money_category.lower():
  user_category_rate = Movie_theater_inflation_rate

elif "gifts" in money_category.lower() or "gifts" in money_category.lower() or "gift" in money_category.lower() or "gift" in money_category.lower():
  user_category_rate = gift_items_inflation_rate

elif "streaming" in money_category.lower() or "streaming" in money_category.lower() or "stream" in money_category.lower() or "stream" in money_category.lower():
  user_category_rate = Streaming_inflation_rate

else:
  user_category_rate = overall_teen_girls_inflation_rate

# Final Report

print("----------- YOUR PERSONAL TEEN INFLATION REPORT -----------")

print(f"The overall teen inflation rate calculated is: {overall_teen_girls_inflation_rate:.2f}%")

print(f"Based on your weekly spending, inflation is costing you an extra ${purchasing_loss:.2f} per week.")

print(f"Your highest spending category is: {money_category} (Inflation Rate: {user_category_rate:.2f}%)")

# User Inflation Rate less/equal/higher than overall inflation rate

if user_category_rate < overall_teen_girls_inflation_rate:
  print(f"Your category inflation rate ({user_category_rate:.2f}%) is LESS than the overall teen average of {overall_teen_girls_inflation_rate:.2f}%.")
  print("You are doing very good! You are not like rest of the average teen girls")

elif user_category_rate == overall_teen_girls_inflation_rate:
  print(f"Your category inflation rate ({user_category_rate:.2f}%) is EQUAL TO the overall teen average of {overall_teen_girls_inflation_rate:.2f}%.")
  print(f"It's alright, at least it's not super high! However, consider cutting down spending on {money_category}")
  print(f"It's suggested to go for Movie Theater since its value is only this: {Movie_theater_inflation_rate:.2f}% ")

elif user_category_rate > overall_teen_girls_inflation_rate:
  print(f"Your category inflation rate ({user_category_rate:.2f}%) is HIGHER than the overall teen average of {overall_teen_girls_inflation_rate:.2f}%.")
  print(f"I highly suggest you to cutdown spending on {money_category} and spend more on Movie Theater since its value is only this:{Movie_theater_inflation_rate:.2f}% ")

else:
  print(f"Your category inflation rate ({user_category_rate:.2f}%) is HIGHER than the overall teen average of {overall_teen_girls_inflation_rate:.2f}%!")
  print(f" Ouch! Your budget is getting hit hard. You should definitely cut down your spending on {money_category} a bit.")
  print(f"To lower your personal inflation impact, try hanging out at Movie Theaters ({Movie_theater_inflation_rate:.2f}%) or using Streaming platforms ({Streaming_inflation_rate:.2f}%) where prices are much safer!")

# Graphs

import matplotlib.pyplot as plt

categories = ["Clothes", "Fast Food", "Movies", "Gifts", "Streaming"]
prices_2025 = [clothing_average_2025, fast_food_average_2025, Movie_theater_average_2025, gift_items_average_2025, Streaming_average_2025]
prices_2026 = [clothing_average_2026, fast_food_average_2026, Movie_theater_average_2026, gift_items_average_2026, Streaming_average_2026]


positions_2025 = [1.0, 2.0, 3.0, 4.0, 5.0]
positions_2026 = [1.3, 2.3, 3.3, 4.3, 5.3]


plt.figure(figsize=(10, 6))


plt.bar(positions_2025, prices_2025, width=0.3, label='2025 Average', color='teal')
plt.bar(positions_2026, prices_2026, width=0.3, label='2026 Average', color='grey')

plt.xlabel('Spending Categories', fontsize=12)
plt.ylabel('Average Price ($)', fontsize=12)
plt.title('Teen Spending: 2025 vs. 2026 Price Comparison', fontsize=14, pad=15,color = 'black',fontweight = 'bold')


center_positions = [1.15, 2.15, 3.15, 4.15, 5.15]
plt.xticks(center_positions, categories)


plt.legend()
plt.tight_layout()
plt.savefig('teen_price_comparison.png', dpi=300)
plt.show()